esphome:
  name: dryfila

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  - platform: esphome
    password: ""

wifi:
  ssid: "SeuWifi"
  password: "SenhaWifi"
  power_save_mode: NONE

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Dryfila Fallback Hotspot"
    password: "senhaWifiEstufa"

captive_portal:

# Enable web interface
web_server:
  port: 80
# Define the onboard LED output
output:
  - platform: gpio
    pin: 8  # GPIO2 is common for onboard LED on ESP32/ESP8266
    id: onboard_led
    inverted: true  # Most onboard LEDs are inverted (LOW = ON)
  # Resistencia
  - platform: slow_pwm
    pin: GPIO1
    id: heating_element
    period: 15s
  # Dummy cool output (can be same as heat or unused pin)
  - platform: template
    id: dummy_cool
    type: float
    write_action:
      - logger.log: "Cool output called"

climate:
  - platform: pid
    name: "Controlador PID"
    id: pid_estufa
    sensor: dht_temp
    default_target_temperature: 40째C
    heat_output: heating_element
    cool_output: dummy_cool
    visual:
      min_temperature: 10
      max_temperature: 80
      temperature_step:
        target_temperature: 1
        current_temperature: 0.1
    control_parameters:
      kp: 10
      ki: 1
      kd: 2
      output_averaging_samples: 5      
      derivative_averaging_samples: 5
    deadband_parameters:
      threshold_high: 2.0째C   
      threshold_low: -1.0째C

button:
  - platform: template
    name: "PID Autotune"
    on_press:
      - climate.pid.autotune: pid_estufa


sensor:
  - platform: dht
    model: DHT11
    pin: GPIO4
    temperature:
      name: "Temperatura"
      id: dht_temp
      filters:
        - sliding_window_moving_average:
            window_size: 3
            send_every: 3
    humidity:
      name: "Umidade"
      id: dht_hum
    update_interval: 10s
  
  - platform: pid
    name: "PID PWM"
    type: RESULT


# Bot찾o teste para acender led da placa
switch:
  - platform: output
    name: "Onboard LED"
    output: onboard_led
    id: led_switch
